name       : qtractor
version    : 0.8.1
release    : 4
source     :
    - http://pilotfiber.dl.sourceforge.net/project/qtractor/qtractor/0.8.1/qtractor-0.8.1.tar.gz : baf14db40d0ea5b6356482b2c5b9e53aeb5e58177f820b408a4cb9e94b4e7adf
license    : GPL-2.0
component  : multimedia.audio
summary    : Qtractor is an audio/MIDI multi-track sequencer application
description: |
    Qtractor is an audio/MIDI multi-track sequencer application
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lilv-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(rubberband)
    - pkgconfig(vorbis)
    - ladspa-devel
    - libmad-devel
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
