name       : qtractor
version    : 0.9.11
release    : 14
source     :
    - https://sourceforge.net/projects/qtractor/files/qtractor/0.9.11/qtractor-0.9.11.tar.gz/download : a0f0c2e288925e8445a6f7d710741645334f6d762123f421395513391c959709
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Qtractor is an audio/MIDI multi-track sequencer application
description: |
    Qtractor is an audio/MIDI multi-track sequencer application
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(aubio)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lilv-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(rubberband)
    - pkgconfig(suil-0)
    - pkgconfig(vorbis)
    - ladspa-devel
    - libmad-devel
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
