name       : qtractor
version    : 0.9.26
release    : 27
source     :
    - https://github.com/rncbc/qtractor/archive/refs/tags/qtractor_0_9_26.tar.gz : bf1f89a805166e99ca4b9bfc66f8bb1d71a258bf611b1e9e90613cd46799e6a4
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Qtractor is an audio/MIDI multi-track sequencer application
description: |
    Qtractor is an audio/MIDI multi-track sequencer application
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(aubio)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lilv-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(rubberband)
    - pkgconfig(suil-0)
    - pkgconfig(vorbis)
    - ladspa-devel
    - libmad-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
