name       : qtractor
version    : 0.9.19
release    : 24
source     :
    - https://github.com/rncbc/qtractor/archive/qtractor_0_9_19.tar.gz : f76bd709abf18d4141b45d4f9d251d61861fc0f982c84061b21778c49bbac216
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Qtractor is an audio/MIDI multi-track sequencer application
description: |
    Qtractor is an audio/MIDI multi-track sequencer application
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(aubio)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lilv-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(rubberband)
    - pkgconfig(suil-0)
    - pkgconfig(vorbis)
    - ladspa-devel
    - libmad-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
