name       : qtractor
version    : 0.9.10
release    : 13
source     :
    - https://sourceforge.net/projects/qtractor/files/qtractor/0.9.10/qtractor-0.9.10.tar.gz/download : 53264077ace74c97c1008e4c5de20a4023a21c9fb0410d515d44d9868539d201
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Qtractor is an audio/MIDI multi-track sequencer application
description: |
    Qtractor is an audio/MIDI multi-track sequencer application
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(aubio)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lilv-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(rubberband)
    - pkgconfig(suil-0)
    - pkgconfig(vorbis)
    - ladspa-devel
    - libmad-devel
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
