name       : qtractor
version    : 0.9.6
release    : 9
source     :
    - https://sourceforge.net/projects/qtractor/files/qtractor/0.9.6/qtractor-0.9.6.tar.gz/download : b72bc8faf74f221f60346577506049786668b97c80c6286d4313e48f28274a1b
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Qtractor is an audio/MIDI multi-track sequencer application
description: |
    Qtractor is an audio/MIDI multi-track sequencer application
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lilv-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(rubberband)
    - pkgconfig(vorbis)
    - ladspa-devel
    - libmad-devel
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
