name       : qtractor
version    : 0.8.0
release    : 1
source     :
    - http://pilotfiber.dl.sourceforge.net/project/qtractor/qtractor/0.8.0/qtractor-0.8.0.tar.gz : 4710f1c9f377b0e2c678517c6c094921b504aec3c16702048d9b611fe930659f
license    : GPL-2.0
component  : multimedia.audio
summary    : Qtractor is an audio/MIDI multi-track sequencer application
description: |
    Qtractor is an audio/MIDI multi-track sequencer application
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lilv-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(rubberband)
    - pkgconfig(vorbis)
    - ladspa-devel
    - libmad-devel
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
